### ISSUE TITLE
renderAsync not waiting for async dispatches

### ISSUE THREAD

**Issue by arensade** [urbanmassage/redux-async-render#1]
Hi,

I find that renderAsync not waiting for async dispatches.

For example an action that call users list from api.
https://github.com/sadeghipour/react-redux-router-dom-ssr/blob/master/src/server.js#L72-L81

any idea?

**Comment by louy** [comment]
Hi,
If you take a look at [line 61](https://github.com/sadeghipour/react-redux-router-dom-ssr/blob/master/src/server.js#L61) you're calling `configureStore` with a list of middleware, but if you look at [line 35](https://github.com/sadeghipour/react-redux-router-dom-ssr/blob/master/src/server.js#L35) this function takes an initial state, which means non of your middleware is being used.
