### ISSUE TITLE
Apply Middleware to store created with serverHelper

### ISSUE THREAD

**Issue by cherya** [urbanmassage/redux-async-render#2]
Redux [createStore](http://redux.js.org/docs/api/createStore.html) takes 3 arguments including [enhancer], but 
```javascript
const finalCreateStore = compose(
  serverHelper
)(createStore);
```
finalCreateStore [takes](https://github.com/urbanmassage/redux-async-render/blob/master/index.ts#L14) only 2 arguments, and ignores 3rd party middlewares (like thunk).
Is it bug or there is a way to apply middleware to created store?

**Comment by louy** [comment]
IIRC you have two options:
```js
const enhancer = compose(serverHelper, thunk);
const finalCreateStore = enhancer(createStore);
const store = createStore(reducer);
```
or
```js
const enhancer = compose(serverHelper, thunk);
const store = createStore(reducer, void 0, enhancer);
```

both achieve exactly the same thing

**Comment by cherya** [comment]
Thank you :)
